### ISSUE TITLE
Could this lib resolve domain through clientip?

### ISSUE THREAD

**Issue by MolenZhang** [abh/geodns#111]
Hi: 
   I`m confused by resolving domians though clientip, which i mean is different client should get the different ip by the same domain. For example,region A(10.17.0.2) resolve example.com with resp of 1.2.3.4, and region B(10.27.0.3) resolve example.com with resp of 6.7.8.9.
   Did i come to the right place?Can grodns support it? Just give me some advise,Thanks!

Best wishes~

**Comment by abh** [comment]
Yes, that is the main use case for GeoDNS!

**Comment by MolenZhang** [comment]
> Yes, that is the main use case for GeoDNS!

pretty cool!
