### ISSUE TITLE
adding GeoIP2 support

### ISSUE THREAD

**Issue by cricsus** [abh/geodns#113]
MaxMind is no more publishing .dat binaries, but .mmdb and .csv instead. The reader for GeoIP2 can be found on [Oschwald's GeoIP2 Golang](https://github.com/oschwald/geoip2-golang).

Alternatively, the [CPP Code for converting .CSV to .DAT](https://github.com/dankamongmen/sprezzos-world/blob/master/packaging/geoip/debian/src/geoip-csv-to-dat.cpp) may work either (Didn't for me).

It'd be great if you switched over to supporting the newest version of GeoIP databases without to have to convert them oneself before.

EDIT:
Apparently it looks for MMDB instead of DAT as I figured later. Please update the docs :)

**Comment by abh** [comment]
thank you @cricsus
