### ISSUE TITLE
Incompatibility with latest dns standarts

### ISSUE THREAD

**Issue by gofort** [abh/geodns#115]
Hi! As I see the current server is not fully compatible with https://dnsflagday.net, is there any plan to fix this?
Report: https://ednscomp.isc.org/ednscomp/2c3e496ec6

**Comment by abh** [comment]
@gofort & @VarunBatralT -- patches are welcome!

**Comment by abh** [comment]
https://ednscomp.isc.org/ednscomp/4508bce97e
