### ISSUE TITLE
Reload geoip database periodically

### ISSUE THREAD

**Issue by abh** [abh/geodns#16]
Once a day or so we should reload the geoip database in case it's changed.

**Comment by abligh** [comment]
In order to reload it, you first have to download the new version. You may or may not be interested in:
  https://github.com/abligh/geoipupdate
which is a pure go-lang apache-licensed geoip update program. Feel free to incorporate it if useful.

**Comment by tydavis** [comment]
I think this can be closed?

**Comment by abh** [comment]
yes, thanks @tydavis!

Closed via #128
