### ISSUE TITLE
status as json

### ISSUE THREAD

**Issue by leifj** [abh/geodns#41]
I'm trying to build a munin-plugin (StatHat isn't for me) and it would be good to have a json-formatted status page so one doesn't have to parse html to get at the counters. 

I guess the "clean" way to do this would be to use the Accept-header but that might be overdoing it.

Thoughts?

I might take a whack at it unless somebody already has/wants to.

**Comment by abh** [comment]
I've merged this now and changed it a little to make it easier to extend. More coming soon. :-)
