### ISSUE TITLE
TTL cannot be set per record

### ISSUE THREAD

**Issue by wmark** [abh/geodns#60]
TTLs for records are being ignored; **GeoDNS** does only take into account the zone's default TTL.

For example, given [test.example.com, lines 32–35](https://github.com/abh/geodns/blob/c4a5ec7f1040197eda4ced46cfb5f25af03cb4a5/dns/test.example.com.json#L32-L35) with the default TTL of 600 and a configured TTL of 601 for **bar.test.example.com**,
I expect this:
```bash
$ ./geodns --port=3053 &

$ dig @127.0.0.1 -p 3053 a bar.test.example.com | grep -A 1 -F "ANSWER SECTION" | cut -f 2 -d ' '
ANSWER
601

$ dig @127.0.0.1 -p 3053 cname cname-long-ttl.test.example.com | grep -A 1 -F "ANSWER SECTION" | cut -f 2 -d ' '
ANSWER
86400

$ kill %1
```

But the result is the default TTL:
```bash
ANSWER
600

ANSWER
600
```

**Comment by abh** [comment]
That's surprising; I thought I had tests for this. I'll have a look, thank you!

**Comment by abh** [comment]
Thank you again for pointing this out.

**Comment by wmark** [comment]
Thank you!
