### ISSUE TITLE
Request forwarder support available ?

### ISSUE THREAD

**Issue by gugansankar** [abh/geodns#65]
Does it has a request forwarder support available ?. Example, if the record is not found on this server, it need to forward the query to some backend resolver as per the forwarder entry.

**Comment by abh** [comment]
It does not and I'm not planning on adding it. You might be able to use dnsdist or something similar to make your setup work:

http://dnsdist.org
http://blog.powerdns.com/2015/03/11/introducing-dnsdist-dns-abuse-and-dos-aware-query-distribution-for-optimal-performance/

**Comment by gugansankar** [comment]
Thanks for your comment. I will have it check this option.
