### ISSUE TITLE
go test have an error

### ISSUE THREAD

**Issue by torfuzx** [abh/geodns#86]
When go test or go build,have an error.

pkg-config --cflags geoip
Package geoip was not found in the pkg-config search path.
Perhaps you should add the directory containing `geoip.pc'
to the PKG_CONFIG_PATH environment variable
No package 'geoip' found
pkg-config: exit status 1

**Comment by torfuzx** [comment]
sorry,I am a fool.First of all, I must install GeoIP Legacy C Library

**Comment by abh** [comment]
Glad you figured it out! :-)
